CREATE TABLE IF NOT EXISTS Clients (
	ClientId 		INTEGER PRIMARY KEY AUTOINCREMENT,
	Prenom			VARCHAR(50),
	Nom				VARCHAR(50),
	Mail			VARCHAR(255) UNIQUE,
	Telephone		VARCHAR(50) UNIQUE
	);

CREATE TABLE IF NOT EXISTS Chambres (
	ChambreId 		INTEGER PRIMARY KEY AUTOINCREMENT,
	Lits			INTEGER NOT NULL,
	Personnes		INTEGER NOT NULL,
	Prix			INTEGER NOT NULL
	);
		
CREATE TABLE IF NOT EXISTS Reservations (
	ReservationId 	INTEGER PRIMARY KEY AUTOINCREMENT,
	ClientId		INTEGER,
	ChambreId		INTEGER,
	DateArrivee		DATE NOT NULL,
	DateDepart		DATE NOT NULL,
	FOREIGN KEY (ClientId) REFERENCES Clients(ClientId)
	FOREIGN KEY (ChambreId) REFERENCES Chambres(ChambreId)
	);
	
CREATE TABLE IF NOT EXISTS Menus (
	MenuId		 	INTEGER PRIMARY KEY AUTOINCREMENT,
	ClientId		INTEGER,
	Entrée			VARCHAR(50) NOT NULL,
	Plat			VARCHAR(50) NOT NULL,
	Dessert			VARCHAR(50) NOT NULL,
	FOREIGN KEY (ClientId) REFERENCES Clients(ClientId)
	);
